

Option.create(name: "provincie", museum_id:nil, key: "", value:"")
Option.create(name: "provincie", museum_id:nil, key: "AG", value:"Agrigento")
Option.create(name: "provincie", museum_id:nil, key: "AL", value:"Alessandria")
Option.create(name: "provincie", museum_id:nil, key: "AN", value:"Ancona")
Option.create(name: "provincie", museum_id:nil, key: "AO", value:"Valle d'Aosta/Vallée d'Aoste")
Option.create(name: "provincie", museum_id:nil, key: "AP", value:"Ascoli Piceno")
Option.create(name: "provincie", museum_id:nil, key: "AQ", value:"L'Aquila")
Option.create(name: "provincie", museum_id:nil, key: "AR", value:"Arezzo")
Option.create(name: "provincie", museum_id:nil, key: "AT", value:"Asti")
Option.create(name: "provincie", museum_id:nil, key: "AV", value:"Avellino")
Option.create(name: "provincie", museum_id:nil, key: "BA", value:"Bari")
Option.create(name: "diocesi", museum_id:nil, key: "051", value:"ACERENZA")
Option.create(name: "diocesi", museum_id:nil, key: "160", value:"ACERRA")
Option.create(name: "diocesi", museum_id:nil, key: "651", value:"ACIREALE")
Option.create(name: "diocesi", museum_id:nil, key: "501", value:"ACQUI")
Option.create(name: "diocesi", museum_id:nil, key: "756", value:"ADRIA - ROVIGO")
Option.create(name: "diocesi", museum_id:nil, key: "659", value:"AGRIGENTO")
Option.create(name: "diocesi", museum_id:nil, key: "502", value:"ALBA")
Option.create(name: "diocesi", museum_id:nil, key: "301", value:"ALBANO")
Option.create(name: "diocesi", museum_id:nil, key: "351", value:"ALBENGA - IMPERIA")
Option.create(name: "diocesi", museum_id:nil, key: "512", value:"ALESSANDRIA")